---
title: "Homework 5"
author: "Dionna Attinson"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
library(viridis)
library(tidyverse)
library(leaflet)
library(gridExtra)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
library(imputeTS)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```
## Question 1 
```{r}
replacenavalues = function(x) { 
  if (is.numeric(x)) {
    (na_mean(x, option = "mean", maxgap = Inf)) } 
  else if (is.character(x)) {
    (replace_na(x, "virginica"))}
}
```

```{r}
output = map(iris_with_missing, replacenavalues)
```
## Question 2
```{r}
df1 =  
  tibble(Participants = list.files(path = "data/", pattern = "csv", all.files = TRUE, full.names = TRUE)) %>%
  mutate(data = map(Participants, read_csv)) %>% 
  unnest() 
```

```{r}
df2 =  
  df1 %>% 
  mutate(
    Participants = str_remove(Participants,".csv"),
    Participants = str_remove(Participants,"data//")) %>%  
pivot_longer(
  week_1:week_8,
  names_to = "Week",
  names_prefix = "week_",
  values_to = "Values")
  
```

```{r}
df3=
 df2 %>% 
 mutate(
 Participants2 = Participants) %>% 
 separate(Participants, into=c("Arm", "Subject_ID"), sep="_") 
```

```{r}
df3 %>% 
ggplot(aes(x = Week, y = Values, group = Participants2, color = Arm)) + 
geom_line() +
  viridis::scale_color_viridis(
    name = "Arm", 
    discrete = TRUE, 
    option = "viridis"
  ) + 
  theme_minimal() +
  labs(
    x = "Week",
    y = "Values", 
    title = "Progression of Subjects over Eight Weeks")
```







